apiVersion: batch/v1
kind: Job
metadata:
  name: philosopher-${YOIK_RESOURCE_ID}-migrations-${PHILOSOPHER_VERSION}
spec:
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
      - name: ghcr
      containers:
        - name: app
          image: ${YOIK_RESOURCE_IMAGE}-dev
          command: ["/bin/sh", "-c"]
          args: ["aerich upgrade"]
          env:
          - name: DEBUG
            value: "false"
          - name: REDIS_URL
            valueFrom:
              secretKeyRef:
                name: philosopher-secrets
                key: redis-url
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: philosopher-secrets
                key: db-host
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: philosopher-secrets
                key: db-port
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: philosopher-secrets
                key: db-user
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: philosopher-secrets
                key: db-password
          - name: DB_NAME
            value: philosopher-${YOIK_RESOURCE_ID}
          - name: AUTH0_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: philosopher-secrets
                key: auth0-client-id
          - name: AUTH0_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: philosopher-secrets
                key: auth0-client-secret
