name: Check for lint and format errors

on:
  push:
    tags-ignore:
      - "v1.*"
    paths:
      - ".pylintrc"
      - ".style.yapf"
      - "Pipfile"
      - "app/**"

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pipenv-${{ hashFiles('Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pipenv-
    
    - name: Setup Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: "3.9"
    
    - name: Setup pipenv
      run: pip install --upgrade pipenv
    
    - name: Install dependencies
      run: pipenv install --dev
    
    - name: Check for lint errors
      run: pipenv run lint
    
    - name: Check for format errors
      run: pipenv run format:check
